### ISSUE TITLE
Add usage and ENV check in main

### ISSUE THREAD

**Issue by runseb** [skippbox/kubewatch#14]
The main does not have any usage

plus it does not check whether the ENV var for SLACK token and channel are presents at startup...

**Comment by runseb** [comment]
the side effect, is that if the eventloop does not see any events it won't create the handler where the SLACK connection is made.

So if the vars are not set, it won't be detected unless a k8s event is trigged.

Bottom line, create a help usage and check for KW_SLACK_TOKEN and KW_SLACK_CHANNEL in main.go

**Comment by Gnouc** [comment]
@runseb I don't think checking for ENV vars in `main` is practical. We can apply different handlers for `kubewatch`, not just slack. So crashing `kubewatch` because of missing slack related ENV variables is no a good ideal IHMO.

**Comment by runseb** [comment]
I do think we need to refactor main to have a basic CLI.
Assuming we start supporting different handlers, we need to be able to specify them on start.
something like `kubewatch --slack` or `kubewatch --notify=slack`

we could pass the toke on the CLI:

`kubewatch --slack --slack-token= --slack-channel=` or get them from ENV var.

**Comment by Gnouc** [comment]
close due to https://github.com/skippbox/kubewatch/pull/17
