### ISSUE TITLE
Need to optimize the Dockerfile.run

### ISSUE THREAD

**Issue by runseb** [skippbox/kubewatch#19]
I had to use alpine to get the ca-certificates bundle, otherwise post to SLACK might fail due to missing CA.

We need to optimize that file so the image is smaller. I did it quickly and it reached ~500MB.

**Comment by Gnouc** [comment]
@runseb Are you sure about the size, maybe you're look at the `kubewatch-builder`, adding ca is not big, here what I got in my machine:

```
docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kubewatch           latest              37a79fe52f0d        12 seconds ago      39.27 MB
```

**Comment by runseb** [comment]
My bad it is 39MB, closing this
