### ISSUE TITLE
Filters for events

### ISSUE THREAD

**Issue by runseb** [skippbox/kubewatch#24]
The bot is now quite chatty and some messages are not well formatted.

We need to break up the filtering and formatting of events from the general handler.

Ideally we could easily add simple configuration that only send notifications for configured events. For example a yaml file with:

[reason]
Created

would only send notifications for events with the reason 'created'.

We could support wildcard:

[reason]
*

**Comment by Gnouc** [comment]
Close via https://github.com/skippbox/kubewatch/pull/27

**Comment by yosbeleg89** [comment]
@Gnouc is it possible to use this feature with the helm chart? Thanks
