### ISSUE TITLE
Investigate the controller framework

### ISSUE THREAD

**Issue by sebgoa** [skippbox/kubewatch#25]
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/controller.go

**Comment by runseb** [comment]
I am raising this to P0. I think with this framework pkg we should be able to catch events for all objects in k8s.

Also we should be able to set the date range. Right now if we run kubewatch we start notifying Slack of all events ever....

What we really want to do is to notify Slack for events that occur from the time kubewatch starts forward...

**Comment by Gnouc** [comment]
@runseb Yep, I saw this one, too.

But I feel this package is for internal usage only. AFAICT, we need to initialize configuration like `kube-apiserver` if we want to use this one.

Let me read the code more thoroughly.

**Comment by ngtuna** [comment]
Hey @Gnouc , any progress update on this issue?

**Comment by Gnouc** [comment]
@ngtuna: I verify for the point I showed you in our last call.

The controller framework is only used for catching events for each k8s resource, not all. If we do use controller framework, we must create controllers for each type of resource, which isn't better than using the API for each resource (Example for `Service`, we can use `/api/v1/watch/services?watch=true` to observe service changed).

**Comment by ngtuna** [comment]
Figured out `controller/framework` seems to be deprecated in k8s master, and it used `cache/reflector` for watching changes. Because #39 also uses `cache/reflector`, once it is solved, this also could be closed.

**Comment by ngtuna** [comment]
Close via #45
