### ISSUE TITLE
[discuss] Having kubewatch cli to control kubewatch daemon

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kubewatch#31]
I found in some cases user has a need to reconfigure filters to get what he want to see while kubewatch is still running. What do you think if we add `kubewatch cli` (like kubectl) in order to control kubewatch daemon ? Some more actions to be considered to declare in `kubewatch cli`:

- start/stop/restart kubewatch daemon
- change slack message format
- create/list/delete handles, specify handle

**Comment by Gnouc** [comment]
@ngtuna After our call, I realize that `kubewatch` main feature is processing event *real time*. If we change `kubewatch` to `server/client` model, then each client run will spawn an `EventLoop` instead of server spawned at start time in current implementation.

**Comment by ngtuna** [comment]
close as it's out of scope
