### ISSUE TITLE
Instead of using slack token, we can use webhooks?

### ISSUE THREAD

**Issue by SydOps** [skippbox/kubewatch#57]
I guess the slack token used in kubewatch is API tokens which is binding with user account directly. 

https://get.slack.help/hc/en-us/articles/215770388-Create-and-regenerate-API-tokens

But I prefer to support incoming webhooks, so I don't worry if someone can represent me to do something bad using my token, if I expose it accidently. 

https://api.slack.com/incoming-webhooks

https://my.slack.com/services/new/incoming-webhook/

**Comment by ngtuna** [comment]
@SydOps yes incoming webhook is also possible. Originally kubewatch was implemented to run with incoming webhook but then I thought using slack token would be more convenient for users. For securing token we can use k8s secret. I can make a commit for that. You're also very welcome to send us a PR :-)

**Comment by SydOps** [comment]
@ngtuna 

Sure, why not, but not sure which file I should target to update it? Any hints?

**Comment by ngtuna** [comment]
@SydOps Great 👍 . So I have a hint for you:

In this function https://github.com/skippbox/kubewatch/blob/master/config/config.go#L109 I made another way to set kubewatch parameters via envvars. You should first add 2 lines for reading slack channel & token.

Then make kubewatch reading secret objects instead of configmap. Take a look on this reference: http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-environment-variables

**Comment by SydOps** [comment]
@ngtuna Have no time to work on it recently. If you'd like to fix it, i leave it open, otherwise I close it directly.

**Comment by ngtuna** [comment]
@SydOps No just keep it open as I see it's a must-have feature. Let me take it.

**Comment by ngtuna** [comment]
I'm gonna close it now. Tested!

**Comment by adusumillipraveen** [comment]
@ngtuna @ozbillwang Can you please help me how this can be used with incoming webhooks? Can we still be able to override slack channel and username while using slack webhooks

**Comment by bjorn-ali-goransson** [comment]
@adusumillipraveen like this:

    helm install --set webhook.enabled=true,webhook.url="...",slack.enabled=false stable/kubewatch
