### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by edevil** [skippbox/kubewatch#63]
Hello.

I've experimented with the bot and used the default kubernetes deployment descriptor which fetched the "0.0.1" tag of the docker image. WIth this version I get pod changes notifications and service change notifications (although I get a log of spurious service changes for some reason). I've also tried the latest code from the repository which has a lot of commented out code and it seems only pod notifications are working.

What is the current state of the project? Is there some refactoring going on?

**Comment by sebgoa** [comment]
Hi @edevil unfortunately we don't really maintain this project anymore.

Most of skippbox projects moved to https://github.com/bitnami and we now work a lot on https://github.com/kubeless/kubeless

**Comment by edevil** [comment]
Thank you for the clarification!
