### ISSUE TITLE
Reference Kubeconfig File?

### ISSUE THREAD

**Issue by spirrello** [skippbox/kubewatch#68]
Hi,

Is there a way to point Kubewatch to our kubeconfig file that contains the auth token and K8s API url?

**Comment by ngtuna** [comment]
@spirrello Yes. You can set the envvar `KUBECONFIG`, otherwise kubewatch will use the default `$HOME/.kube/config`

**Comment by spirrello** [comment]
Can you advise how to do this?
________________________________

**Comment by spirrello** [comment]
Thanks...I figured it out.
