### ISSUE TITLE
Improve formatting of SLACK messages

### ISSUE THREAD

**Issue by runseb** [skippbox/kubewatch#7]
Look at how to better format the messages sent to SLACK.
Maybe add color ...:)

For instance we could color code the the messages based on their type or status of the object.

**Comment by Gnouc** [comment]
Object type should be easier, only `Normal` or `Warning` for now, corresponding with `good` and `warning` color for slack.

**Comment by Gnouc** [comment]
close due to https://github.com/skippbox/kubewatch/pull/18
